### PR TITLE
Fixes search not working due to appended string. Fixes #88

### LINKED ISSUE #88: Search terms in the store get a "?platform" query string appended
When I want to search for apps in the Pebble Appstore and enter a search term it always gets "?platform" appended before it is transmitted to the store search.
That always gets me no result. I can remove the "?platform" in the inputbox within the store and after that search works. But it is annoying to have to do that again and again.

### PR DESCRIPTION
**Pull request by smurfy**

### CODE REVIEW

**Comment by abranson** [comment]
Could this get finalized? I've tested it with and without the equals and it's fine. Until this patch is merged, search doesn't work without removing the extra '?platform' from the query and even then installation isn't possible because of the missing platform parameter.

**Comment by smokku** [comment]
@abranson Could you update the PR?

**Comment by abranson** [comment]
Can I edit this one somehow, or do I have to create another?

**Comment by smokku** [comment]
Please create another referencing this one.

**Pull request closed without merging**
