### PR TITLE
Switch music volume controls to alter the system volume.

### PR DESCRIPTION
**Pull request by abranson**
Solves smokku/pebble#48.

I know you're not keen, but it's really cool, and in line with the android behaviour.

### CODE REVIEW

**Comment by smurfy** [comment]
As far as i can tell this PR removes the "/org/mpris/MediaPlayer2" call completely.
I think this is not a good idea. The [mpris spec](http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Volume) defines volume change support and the stock sailfish mediaplayer just does not support it.

So my suggestion would be to add a config parameter to enable either mpris volume control or system volume control.

**Comment by abranson** [comment]
Right, preference added, and I also added to the service switcher to check if setting the volume through mpris has any effect on the value, and it will only default to pulseaudio if not.

**Comment by abranson** [comment]
Ok, updated and squashed. MPRIS test gone, which has made it a lot simpler. The only thing I didn't do was the QScopedPointer, as I haven't been able to figure out what the assigment should look like yet. From what I read it should be a straight switch in the header, but the compiler complains about the assignment. C++ slightly less rusty now.

**Comment by smokku** [comment]
The only way to wrap a plain pointer to smart pointer is with the constructor.
So it's best to wrap in initialization list.
But if you really need to assign, to wrap in flight use:

    some_scoped_pointer = QScopedPointer<QSomething>(real_pointer);

**Comment by smokku** [comment]
I just noticed that QDbusConnection is not a QObject, so QScopedPointer would not work anyway. ;-)

Thank you for your submission. :)

**Comment by abranson** [comment]
You're welcome!

**Pull request merged**
