### PR TITLE
To be smooth the Scroll of PebbleStoreView

### PR DESCRIPTION
**Pull request by helicalgear**
PebbleStoreView on AppStorePage is a little bit difficult to scroll.
I think that the issue may happen when the scrollable conponent(webview) placed on scrollable conponent(SilicaFlickable).

### CODE REVIEW

**Comment by smokku** [comment]
Does this change mean that one will be able to pull menu down by pulling on the buttons area only?

**Comment by helicalgear** [comment]
I use this app very very conveniently.
But I felt that the reaction of scrolling in a PebbleStoreView part of a AppStorePage is not suitable.
I once experienced similar case when I placed the scrollable component (like PebbleStoreView) in the SilicaFlickable{}.
This is just only my suggestion to solve it by separating the "SilicaFlickable" and "PebbleStoreView".

Unfortunately I am not good at English conversation.
I'm sorry if my grammar is wrong and you don't understand the meaning.

**Comment by smokku** [comment]
We are aware of the jerky scrolling of store view, with no good idea how to solve it.
I'm reluctant to merging this workaround, as it will break the expected experience of being able to pull the puley menu by pulling wherever on screen.

**Comment by awlx** [comment]
Maybe we could move the pulley menu to the right side. I don't think that having multiple pull actions stacked is a very good solution as it causes problems in handling. And the store experience is not that good because of it. 

Maybe you can use the nicklist of IRC for Sailfish as inspiration on how to make the menu better.

**Comment by smokku** [comment]
- There is no side-menu in Silica: https://sailfishos.org/develop/docs/silica/sailfish-silica-all.html/#menus
- This is against SailfishOS design
- There is no place for side menu on phone portrait screen layout

**Comment by awlx** [comment]
Yeah, I know that there is no side-menu in Silica. But we need a workaround for the current problem. Maybe you could place the Logout button in the settings menu. And the search next to Faces or a simple line to type search text beneath Apps/Faces. This would also fix the scrolling problem.

**Comment by abranson** [comment]
Personally, I'd expect the web view to scroll if my finger was on the web view, and the pulley menu to appear if it were on the title. That avoids the annoying Sailfish problem of wanting to access the menu when you're at the end of a long list. If the webview is at its top, then i sort of would expect the pulley to activate, but that's far less annoying than the funny left-then-down swish I have to do to scroll the webview now.

**Comment by smokku** [comment]
oh well... it's better than before at least :-)

**Pull request merged**
